local VO = vim.opt
VO.syntax = 'on'
VO.ruler = true
VO.relativenumber = true
VO.visualbell = false
VO.showtabline = 2
VO.autoindent = true
VO.smartindent = true
VO.termguicolors = true
VO.wrap = false
VO.scrolloff = 8
VO.autoread = false
VO.hidden = true
VO.background = "dark" -- or "light" for light mode
VO.backup = false
VO.ignorecase = true
VO.splitbelow = true
VO.splitright = true
VO.encoding = "utf-8"
VO.laststatus = 2
VO.guicursor = ""
VO.updatetime = 300
VO.cmdheight = 2
